version: '3.7'
services:
  nvim:
    environment:
      - bootstrap.memory_lock=true
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pde 
    entrypoint: /bin/bash
    tty: true
    volumes:
    - ~/Documents/Sud/Learning:/home/node/zmount
    ports:
    - '4004:4004'
    - '4005:4005'
    - '8000:8000'
    privileged: true